language: java
script: mvn verify
jdk:
- oraclejdk8
notifications:
  slack:
    secure: GESPo35uuqCasPtrw7zsJOi32PruCUPlls+wcSU+KWttcHNLfW5P1b4HReDRpbQFmoA2qcCw37Cq3JmeWBdFEITPMZw0IMSGAPr8lroIpq5CQJij0gxWXkJk14Y7jjeCRBOLmq4cCFUpYDScTX08+BWSMWtsTgpSEr3FZas4ond/4nc4Wh7eTDb+phs/FOzofIKeKtwvl0Y7MqyiKvTXfbU0gTG63ICWKAbtpyRIVj2J+ZwyNIpDIFR/5UmKHoxUXsBn51RQkllMtPXb5XgTXKce4DRlvcf6ytP4P0mN2ZmSkpZ3LN1OJDOIKgYd/kQh/HcJ3B2CwNwSA4aD9fIMIuU0DN1Pf4h9p6n/M6cQsQ02qKFt7B9q5DzHtLLStJ47cYhFqWSrLcy/PrZP0nHeZTBRU9qfF2LtzDahAeApMhsnUCg7VkPcMtfgzOdLGs47XGKDwPgyXKKo6QYXMlMQItxhr3ZYde7q8oX1hOZreRgZR8LvdwOYdf5leYX6Vo/1u44eLu9jkZm5wDFUxkH5F2TmQccyirbpxSPwjrdKDAKUPnY7eEWvFJY6KLp++fVMWHFjWlvLjCNixo6frhFxhyxf4csNOjnAyzrDPgJ5s2bud9rCSLApiM+l8mE6lHzI9ZM8ndBduuWCNcLVWy1719pebzO76mwjpIUfUEQ3VqI=
  email: false
